from __future__ import annotations

from pathlib import Path
from typing import Any

from .paths import codex_home_path
from .routing_toml import _toml_string
from .routing_defs import (
    CHILD_ROLES,
    MANAGED_AGENT_MARKER,
    ROLE_AGENT_NAMES,
    ROLE_SPECS,
    RoutingError,
)
from .routing_normalize import normalize_effort
from .util import atomic_write, json_dumps, utc_now


def render_agent_toml(
    role: str, entry: dict[str, Any], *, allow_nested_agents: bool = False
) -> str:
    if role not in CHILD_ROLES:
        raise RoutingError(f"Cannot render unknown child role: {role}")
    spec = ROLE_SPECS[role]
    agent_name = str(entry.get("agent") or ROLE_AGENT_NAMES[role])
    lines = [
        MANAGED_AGENT_MARKER,
        "# Generated by JAM Mode 0.3. Edit JAM routing settings instead of this file.",
        f"# role = {role}",
        f"name = {_toml_string(agent_name)}",
        f"description = {_toml_string(spec['description'])}",
    ]
    model = str(entry.get("model") or "").strip()
    effort = normalize_effort(entry.get("effort"))
    if model:
        lines.append(f"model = {_toml_string(model)}")
    if effort:
        lines.append(f"model_reasoning_effort = {_toml_string(effort)}")
    lines.append(f"sandbox_mode = {_toml_string(spec['sandbox'])}")
    instructions = spec["instructions"]
    if allow_nested_agents:
        instructions = instructions.replace("Do not spawn additional agents.", "")
        instructions = instructions.replace("Do not spawn agents.", "")
        instructions = instructions.rstrip() + """

Ultra nested delegation is explicitly enabled for this role. You may delegate at
most one read-only helper at a time, one generation deep, and only for a clearly
bounded part of the parent's assignment. Do not delegate writes, invoke JAM
campaign controls, broaden scope, or let a helper decide campaign continuation.
You remain responsible for validating and returning the combined result.
"""
    instructions = instructions.replace('"""', '\\"\\"\\"')
    lines.extend(
        [
            'developer_instructions = """',
            instructions,
            '"""',
            "",
        ]
    )
    return "\n".join(lines)


def managed_agent_paths(codex_home: Path | None = None) -> dict[str, Path]:
    base = (codex_home or codex_home_path()) / "agents"
    return {
        role: base / f"{ROLE_AGENT_NAMES[role]}.toml" for role in CHILD_ROLES
    }


def project_agent_collisions(workspace: str | Path) -> list[str]:
    agent_dir = Path(workspace).expanduser().resolve() / ".codex" / "agents"
    if not agent_dir.is_dir():
        return []
    collisions: list[str] = []
    for role, agent_name in ROLE_AGENT_NAMES.items():
        candidate = agent_dir / f"{agent_name}.toml"
        if candidate.exists():
            collisions.append(f"{role}: {candidate}")
    return collisions


def ensure_managed_agents(
    resolved_routing: dict[str, Any],
    *,
    codex_home: Path | None = None,
    workspace: str | Path | None = None,
) -> dict[str, str]:
    """Install/update JAM-prefixed custom agents without touching unrelated config."""

    if workspace is not None:
        collisions = project_agent_collisions(workspace)
        if collisions:
            raise RoutingError(
                "Project-scoped custom agents would override JAM's managed agents. "
                "Rename or remove these files before starting the campaign: "
                + "; ".join(collisions)
            )

    paths = managed_agent_paths(codex_home)
    collisions = []
    for path in paths.values():
        if not path.exists():
            continue
        existing = path.read_text(encoding="utf-8", errors="replace")
        if MANAGED_AGENT_MARKER not in existing:
            collisions.append(str(path))
    if collisions:
        raise RoutingError(
            "Refusing to overwrite non-JAM custom agent files: "
            + "; ".join(collisions)
            + ". Rename them or choose a different Codex home."
        )

    output: dict[str, str] = {}
    for role, path in paths.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        entry = (resolved_routing.get("roles") or {}).get(role) or {
            "agent": ROLE_AGENT_NAMES[role],
            "model": None,
            "effort": None,
        }
        atomic_write(
            path,
            render_agent_toml(
                role,
                entry,
                allow_nested_agents=(
                    bool(resolved_routing.get("allow_child_ultra"))
                    and normalize_effort(entry.get("effort")) == "ultra"
                ),
            ),
        )
        output[role] = str(path)

    manifest_path = (codex_home or codex_home_path()) / "jam-mode" / "agents-manifest.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write(
        manifest_path,
        json_dumps(
            {
                "schema_version": 1,
                "generated_at": utc_now(),
                "policy": resolved_routing.get("policy"),
                "validation": resolved_routing.get("validation"),
                "agents": output,
            },
            pretty=True,
        ),
    )
    return output


def inspect_managed_agents(codex_home: Path | None = None) -> dict[str, Any]:
    paths = managed_agent_paths(codex_home)
    agents: dict[str, Any] = {}
    for role, path in paths.items():
        exists = path.exists()
        managed = False
        if exists:
            try:
                managed = MANAGED_AGENT_MARKER in path.read_text(
                    encoding="utf-8", errors="replace"
                )
            except OSError:
                managed = False
        agents[role] = {
            "agent": ROLE_AGENT_NAMES[role],
            "path": str(path),
            "exists": exists,
            "managed": managed,
        }
    return {
        "codex_home": str((codex_home or codex_home_path()).resolve()),
        "agents": agents,
        "ok": all(
            item["exists"] and item["managed"] for item in agents.values()
        ),
    }


def remove_managed_agents(codex_home: Path | None = None) -> list[str]:
    removed: list[str] = []
    for path in managed_agent_paths(codex_home).values():
        if not path.exists():
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if MANAGED_AGENT_MARKER in text:
            path.unlink()
            removed.append(str(path))
    return removed
